[package]
name = "explore-future"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "future"
path = "src/bins/future.rs"

[[bin]]
name = "pin"
path = "src/bins/pin.rs"

[[bin]]
name = "task"
path = "src/bins/task.rs"

[dependencies]
tokio = { version = "1.39.3", features = ["full"] }
